name: manga_reader
description: "一个支持本地阅读和局域网跨设备访问的漫画阅读器"
publish_to: 'none'
version: 1.0.0+2026060612

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^4.2.0
  drift: 2.30.0
  extended_image: ^10.0.1
  file_picker: ^10.3.10
  fluttertoast: ^9.0.0
  get: ^4.7.3
  get_storage: ^2.1.1
  loading_animation_widget: ^1.3.0
  logger: ^2.6.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  photo_view:
    git:
      url: https://github.com/xqs66/photo_view.git
      ref: main
  scrollable_positioned_list: ^0.3.8
  simple_animations: ^5.2.0
  crypto: ^3.0.7
  flutter_slidable: ^4.0.3
  archive: ^4.0.9
  xml: ^6.5.0
  battery_plus: ^6.2.1
  keframe: ^3.0.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  multicast_dns: ^0.3.2
  flutter_foreground_task: ^9.2.2
  sqlite3_flutter_libs: 0.5.32

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: 2.30.0
  build_runner: ^2.4.0

dependency_overrides:
  sqlite3: 2.9.4  #sqlite3.x 之后采用hook方式，运行时无法无法正常下载原生库，所以降级为2.9.4

flutter:
  uses-material-design: true
